# Default values for RKM.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

repository:
  outpost: quay.io/dmlabs/rkm-outpost

operator:
  name: rkm-outpost
  components: cronjob/rkm-outpost
  repository: quay.io/dmlabs/simple-operator
  schedule: "* 6 * * 2"

clusterInformation:
  # Kubernetes cluster information for RKM to collect the correct metrics
  clusterName: kubernetes-cluster-1
  kubeAPIServerPort: 6443
  tz: Europe/Zurich

schedule:
  outpost: "* * * * *"

rkmMissionControl:
  # InfluxDB URL and InfluxDB Name of the RKM mission control
  # NOTE: This chart expects InfluxDB with authentication and you need to create a Kubernetes secret with that information
  # -> kubectl create secret generic rkm-secrets --from-literal=INFLUXDB_USER=<user> --from-literal=INFLUXDB_PW=<password> -n <rkm-namespace>
  influxDBUrl: http://influxdb.example.com
  influxDBPort: 80
  influxDBName: rkm