---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ .Values.operator.name }}
    role: {{ .Values.operator.name }}-operator
  name: {{ .Values.operator.name }}-operator
rules:
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  verbs:
  - get
  - patch